In [1]:
import numpy as np

array verison

In [2]:
print(np.__version__)

2.2.6


multi dimension array

In [3]:
# 0-D array
print(np.array(12))

12


In [4]:
d = np.array([[1,2 ],[2,2]])
print(np.ndim(d))

2


In [5]:
# higher dimension array

d = np.array([1,1,2], ndmin=4)
print(d)

[[[[1 1 2]]]]


array slicing

In [6]:
ar = np.array([1,2,3])
print(ar[0])

1


In [7]:
ar = np.array(
            [
                [
                    [1,2,3,4],
                    [5,6,7,8]
                ]
            ]
        )
print(np.ndim(ar))
print(ar[0,0,1:4])

# ar1 = np.array([[[0,1,1],[0,102,1]],[[1,2],[12]]])

3
[2 3 4]


array datatype and typecasting

In [37]:
arr = np.array([0,2,4,5,6])
print(arr.dtype)

arr_new = np.array([1,3,5], dtype='f')
print(arr_new)

int64
[1. 3. 5.]


In [38]:
arr = arr.astype('U')
print(arr)

['0' '2' '4' '5' '6']


array copy and view 

In [39]:
new = arr.copy()
arr[0] = 'BMW'
print("new: ",new)
print("arr: ",arr)

new:  ['0' '2' '4' '5' '6']
arr:  ['BMW' '2' '4' '5' '6']


In [40]:
vnew = arr.view()
arr[1] = 'Mercedies'
print("vnew:",vnew)
print("arr:",arr)

vnew: ['BMW' 'Mercedies' '4' '5' '6']
arr: ['BMW' 'Mercedies' '4' '5' '6']


Array shape 

In [46]:
arr = np.array([[1,2]])
print(arr.shape)


(1, 2)
